spring:
  application:
    name: UserPassbook
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true
    username: root
    password: luoyu1233
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

  data:
    hbase:
      quorum: localhost:2181
      rootDir:
      nodeParent:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  port: 9528
logging:
  file: log/passbook.log
  level: debug
