server:
  port: 8080

logging:
  level:
    root: warn
    com.yuro: debug
  file: logs/my.log

book:
  name: jvm虚拟机
  author: Oracle
  isbn: ${random.uuid}
  description: ${book.name}, is a good book~~